#!/usr/bin/env python3
import os
import sys

def main():
  files = sys.argv[1:]
  for f in files:
    if not os.path.exists(f):
      continue

    print(os.path.realpath(f))

if __name__ == "__main__":
  main()
